import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Settings, X } from 'lucide-react';
import { useUiStore } from '../store/ui.store';
export const SettingsContainer = () => {
    const { settingsOpen, setSettingsOpen, theme, setTheme } = useUiStore();
    if (!settingsOpen)
        return null;
    return (_jsxs("div", { id: "settingsPanel", className: "fixed left-0 top-0 w-64 h-full bg-zinc-50 dark:bg-zinc-900 border-r border-zinc-200 dark:border-zinc-800 z-40 flex flex-col overflow-y-auto", children: [_jsxs("div", { className: "p-4 border-b border-zinc-200 dark:border-zinc-800 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Settings, { size: 20 }), _jsx("h2", { className: "font-semibold text-zinc-900 dark:text-zinc-100", children: "Settings" })] }), _jsx("button", { onClick: () => setSettingsOpen(false), className: "text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-100", children: _jsx(X, { size: 20 }) })] }), _jsxs("div", { className: "flex-1 p-4 space-y-4", children: [_jsxs("div", { id: "systemContent", className: "space-y-2", children: [_jsx("h3", { className: "font-medium text-zinc-900 dark:text-zinc-100", children: "Appearance" }), _jsx("div", { className: "space-y-2", children: ['light', 'dark', 'system'].map((t) => (_jsxs("label", { className: "flex items-center gap-2 cursor-pointer", children: [_jsx("input", { type: "radio", name: "theme", value: t, checked: theme === t, onChange: () => setTheme(t), className: "cursor-pointer" }), _jsx("span", { className: "text-sm text-zinc-700 dark:text-zinc-300 capitalize", children: t })] }, t))) })] }), _jsxs("div", { id: "networkModeContent", className: "space-y-2", children: [_jsx("h3", { className: "font-medium text-zinc-900 dark:text-zinc-100", children: "Network Mode" }), _jsx("div", { className: "text-sm text-zinc-600 dark:text-zinc-400", children: "Coming soon" })] }), _jsxs("div", { id: "transactionContent", className: "space-y-2", children: [_jsx("h3", { className: "font-medium text-zinc-900 dark:text-zinc-100", children: "Transactions" }), _jsx("div", { className: "text-sm text-zinc-600 dark:text-zinc-400", children: "Coming soon" })] }), _jsxs("div", { id: "configContent", className: "space-y-2", children: [_jsx("h3", { className: "font-medium text-zinc-900 dark:text-zinc-100", children: "Configuration" }), _jsx("div", { className: "text-sm text-zinc-600 dark:text-zinc-400", children: "Coming soon" })] })] })] }));
};
//# sourceMappingURL=SettingsContainer.js.map